version: '2'

services:
  workspace:
    image: node-dev-bundle:7.5.0
    build: ./docker/workspace-image
    ports:
      - 4200:4200
    volumes:
      - ./:/workspace
    command: tail -f /dev/null
    